server:
  port: 8082

spring:
  jpa.hibernate.ddl-auto: update
  database-platform: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://localhost:3306/online_shop
    username: shop-admin
    password: admin
